import type { Metadata } from "next";

import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Event Registration",
  description: "Generated by create next app",
};

export default function EventFormLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
