import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PersistStore from "@/components/PersistStore";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PersistStore>
          {children}
        </PersistStore>
      </body>
    </html>
  );
}
