import type { Metadata } from "next";
import '@/components/MainLayoutGrid'
import MainLayoutGrid from "@/components/MainLayoutGrid";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboadrdLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainLayoutGrid>
      {children}
    </MainLayoutGrid>
  );
}
